name: "🚀 release"

on:
    push:
        branches:
            - main

jobs:
    release:
        name: 🚀 Release
        runs-on: ubuntu-latest
        steps:
            - name: 📚 Checkout
              uses: actions/checkout@v3
            - name: 🟢 Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org
            - name: 🛸 Check status
              run: yarn install
            - name: 🚀 Publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
